name: 'pulumi-actions - Atlantis like automation for Pulumi'
description: 'init, preview and apply pulumi stacks'
branding:
  icon: command
  color: gray-dark
inputs:
  cmd:
    description: 'The Command which should be run'
    required: true
outputs:
  result:
    description: "The complete result from the pulumi-actions command being run"
runs:
  using: 'docker'
  image: 'docker://ghcr.io/lowkey-who/pulumi-actions:90e36ceb3afbbcf90f5ad9d5f3fcc1713ebea99e-github-action'
  args:
    - ${{ inputs.cmd }}