name: Comment Workflow

on:
  issue_comment:
    types:
      - created

jobs:
  comment_job:
    name: pulumi-actions
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, 'pulumi-actions')   
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: preview stack when comment on PR
        uses: lowkey-who/pulumi-actions@main
        env:
          pulumi_cloud_token: ${{ secrets.PuluToken }}
          passphrase: ${{ secrets.Passphrase }}
        with:
          cmd: ${{ github.event.comment.body }}